# Generated by Django 4.0.3 on 2022-03-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_customusuario_teve_cvd'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusuario',
            name='co_gp',
            field=models.CharField(max_length=15, null=True, verbose_name='Codigo atendimento'),
        ),
    ]
