# Generated by Django 4.0.3 on 2022-03-21 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_customusuario_co_gp'),
    ]

    operations = [
        migrations.CreateModel(
            name='GruposAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, verbose_name='Nome')),
                ('codigo', models.CharField(max_length=20, null=True, verbose_name='Codigo')),
            ],
        ),
        migrations.RemoveField(
            model_name='customusuario',
            name='co_gp',
        ),
        migrations.RemoveField(
            model_name='customusuario',
            name='gp_atendimento',
        ),
        migrations.AddField(
            model_name='customusuario',
            name='id_gp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.gruposatendimento'),
        ),
    ]
